name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      VERCEL_ORG_ID: team_mE6R9KnF9M1zrHLsjG0bTCvG
      VERCEL_PROJECT_ID: prj_6O1DYZrpoq2O2hAxwstHGolvFf9y

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --yes --token "${{ secrets.VERCEL_TOKEN }}"